### ISSUE TITLE
AttributeError: 'EfficientNetFeatures' object has no attribute 'act1'

### ISSUE THREAD

**Issue by qqc22111** [gangweiX/IGEV-plusplus#1]
The problem description is below, how should I resolve this problem?
Unexpected keys (bn2.bias, bn2.num_batches_tracked, bn2.running_mean, bn2.running_var, bn2.weight, classifier.bias, classifier.weight, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.
Traceback (most recent call last):
  File "D:\Project\BinocularStereoVision\IGEV-plusplus\demo_imgs.py", line 90, in <module>
    demo(args)
  File "D:\Project\BinocularStereoVision\IGEV-plusplus\demo_imgs.py", line 30, in demo
    model = torch.nn.DataParallel(IGEVStereo(args), device_ids=[0])
  File "D:\Project\BinocularStereoVision\IGEV-plusplus\core\igev_stereo.py", line 107, in __init__
    self.feature = Feature()
  File "D:\Project\BinocularStereoVision\IGEV-plusplus\core\extractor.py", line 333, in __init__
    self.act1 = model.act1
  File "D:\Anaconda\Anaconda3\envs\MedSAM\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'EfficientNetFeatures' object has no attribute 'act1'

**Comment by gangweiX** [comment]
pip install timm==0.5.4

**Comment by gangweiX** [comment]
please install the corresponding timm version.
